### ISSUE TITLE
warnings under linux with gcc

### ISSUE THREAD

**Issue by jensgerlach** [jensgerlach/dataDictionary#22]
EuroradioMessage.cpp: In function ‘EuroradioMessagePtr EuroradioMessage_Decoder(Bitstream&)’:
EuroradioMessage.cpp:548:55: warning: ‘messageID.MessageHeader::NID_MESSAGE’ may be used uninitialized in this function [-Wmaybe-uninitialized]
             std::cout << "NID_MESSAGE " << +messageID.NID_MESSAGE << std::endl;

**Comment by lapawczykt** [comment]
PacketHeaders are now initialized with the value 0 for NID_PACKET.
0 however matches two Packets, maybe we can come up with a better solution.
